export const products: any[] = [
{
  id:'1',
  name:'Cokies and Cream',
  price: 39,
  cookTime: '5-10',
  favorite: true,
  origins: ['Tabaco City'],
  stars: 5.0,
  imageUrl: 'assets/milktea-default.jpg',
  tags:['Classic Bobbatea', 'Milktea', 'Cookies and Cream'],
},
{
  id:'2',
  name:'Dark Chocolate',
  price: 39,
  cookTime: '5-10',
  favorite: true,
  origins: ['Tabaco City'],
  stars: 4.5,
  imageUrl: 'assets/milktea-default.jpg',
  tags:['Classic Bobbatea', 'Milktea', 'Dark Chocolate'],
},
{
  id:'3',
  name:'Double Dutch',
  price: 39,
  cookTime: '5-10',
  favorite: false,
  origins: ['Tabaco City'],
  stars: 4.0,
  imageUrl: 'assets/milktea-default.jpg',
  tags:['Classic Bobbatea', 'Milktea', 'Double Dutch'],
},
{
  id:'4',
  name:'Red Velvet',
  price: 39,
  cookTime: '5-10',
  favorite: true,
  origins: ['Tabaco City'],
  stars: 4.3,
  imageUrl: 'assets/milktea-default.jpg',
  tags:['Classic Bobbatea', 'Milktea', 'Red Velvet'],
},
{
  id:'5',
  name:'Taro',
  price: 39,
  cookTime: '5-10',
  favorite: true,
  origins: ['Tabaco City'],
  stars: 5.0,
  imageUrl: 'assets/milktea-default.jpg',
  tags:['Classic Bobbatea', 'Milktea', 'Taro'],
},
{
  id:'6',
  name:'Winter Melon',
  price: 39,
  cookTime: '5-10',
  favorite: false,
  origins: ['Tabaco City'],
  stars: 4.5,
  imageUrl: 'assets/milktea-default.jpg',
  tags:['Classic Bobbatea', 'Milktea', 'Winter Melon'],
}
]
export const tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'Classic Bobbatea', count: 6 },
  { name: 'Meals', count: 0 },
  { name: 'Snacks', count: 0 }
]

export const sample_users: any[] =[
  {
    name: "Admin",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];
